version: '3.0'
services:
 mongo:
  image: mongo:latest
  container_name: yeshenko-database
  ports:
   - "27017:27017"
  volumes:
   - ./src/database:/data/db
 app:
  build: .
  image: mongodb:latest
  container_name: yeshenko-java
  depends_on: 
   - mongo
  links:
   - mongo
